disallowed-types = [
    # Uses waitpid, which conflicts with the zombie reaper
    "std::process::Command",
    "std::process::Child",
]
disallowed-methods = [
    # conflicts with the zombie reaper
    "libc::waitpid",
    # allow-invalid is necessary because of a false positive from clippy
    { path = "beam_init::system::waitpid", allow-invalid = true },
]
