[package]
name = "beam-init"
version.workspace = true
edition.workspace = true

[dependencies]
beam-init-api = { path = "../beam-init-api" }
beam-init-client = { path = "../beam-init-client" }

clap.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
futures-core.workspace = true
libc.workspace = true
async-stream.workspace = true
axum.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
mio.workspace = true
clap_complete.workspace = true

[lints]
workspace = true
